-- Seed Data for Course Management App
-- Run: mysql -u root -proot-pass course_management < seed.sql
-- Note: User ID 1 is automatically super_admin via backend logic

-- Create first user (will be super_admin by code, id=1)
INSERT INTO users (username, email, password, bio) VALUES 
('Admin User', 'admin@knowway.com', '$2a$10$rQnM1234567890abcdefgOxyzABCDEFGHIJKLMNOPQRSTUVWXYZ12', 'Platform Administrator');

-- Create teacher accounts (can be promoted via admin panel)
INSERT INTO users (username, email, password, role, bio) VALUES 
('John Smith', 'john@instructor.com', '$2a$10$rQnM1234567890abcdefgOxyzABCDEFGHIJKLMNOPQRSTUVWXYZ12', 'teacher', 'Senior Full Stack Developer with 10+ years of experience'),
('Sarah Johnson', 'sarah@instructor.com', '$2a$10$rQnM1234567890abcdefgOxyzABCDEFGHIJKLMNOPQRSTUVWXYZ12', 'teacher', 'UI/UX Designer and Creative Director'),
('Mike Chen', 'mike@instructor.com', '$2a$10$rQnM1234567890abcdefgOxyzABCDEFGHIJKLMNOPQRSTUVWXYZ12', 'teacher', 'Digital Marketing Expert and Growth Hacker');

-- Development Courses (by John Smith - user_id: 2)
INSERT INTO courses (title, short_description, description, category, duration, price, discount_price, level, status, image_url, total_lessons, total_students, rating, requirements, what_you_learn, who_is_for, user_id) VALUES
('The Complete React Developer Course', 'Master React with hooks, redux, and real projects', 'Learn React by building real-world applications. This course covers everything from React basics to advanced patterns including hooks, context, Redux, and testing.', 'dev', 40, 89.99, 12.99, 'beginner', 'active', 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800', 245, 125890, 4.7, 'Basic HTML, CSS, and JavaScript knowledge\nA computer with internet access\nNo prior React experience needed', 'Build powerful React applications from scratch\nMaster React Hooks and functional components\nHandle state with Redux and Context API\nTest React applications', 'Beginners who want to learn React\nJavaScript developers expanding their skills\nDevelopers building modern web apps', 2),

('Node.js: The Complete Guide', 'Build scalable backend services with Node.js', 'Master Node.js and build fast, scalable network applications. Learn REST APIs, GraphQL, authentication, databases, and deployment.', 'dev', 35, 94.99, 13.99, 'intermediate', 'active', 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=800', 320, 89540, 4.8, 'JavaScript fundamentals\nBasic programming concepts', 'Build REST and GraphQL APIs\nImplement authentication and authorization\nWork with MongoDB and SQL databases\nDeploy applications to production', 'JavaScript developers\nFrontend devs learning backend\nAnyone interested in server-side development', 2),

('Python for Data Science and Machine Learning', 'Complete Python bootcamp for data science', 'Learn Python programming and apply it to data science, machine learning, and AI. Covers NumPy, Pandas, Matplotlib, Scikit-Learn, and TensorFlow.', 'dev', 55, 129.99, 14.99, 'intermediate', 'active', 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=800', 380, 156000, 4.6, 'Basic programming experience helpful\nNo Python knowledge required', 'Master Python programming from basics to advanced\nAnalyze data with NumPy and Pandas\nCreate visualizations with Matplotlib\nBuild machine learning models', 'Aspiring data scientists\nDevelopers interested in ML/AI\nAnalysts wanting to automate tasks', 2),

('JavaScript: Understanding the Weird Parts', 'Deep dive into JavaScript internals', 'Go deep inside the JavaScript engine and understand how the language really works. Closures, prototypes, the event loop, and more.', 'dev', 12, 49.99, NULL, 'advanced', 'active', 'https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?w=800', 85, 245000, 4.9, 'Basic JavaScript knowledge\nSome programming experience', 'Understand JavaScript at a deep level\nMaster closures, prototypes, and scope\nDebug code more effectively\nWrite cleaner, more efficient code', 'JavaScript developers of all levels\nDevelopers preparing for interviews\nAnyone curious about JS internals', 2),

('Git and GitHub Masterclass', 'Version control for professionals', 'Everything you need to know about Git and GitHub for professional development teams. Branching strategies, pull requests, and collaboration workflows.', 'dev', 8, 0.00, NULL, 'beginner', 'active', 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=800', 48, 380000, 4.8, 'Basic command line knowledge\nNo Git experience needed', 'Master Git commands and concepts\nCollaborate using GitHub\nHandle merge conflicts confidently\nUse Git in professional workflows', 'Developers new to version control\nTeams improving their workflow\nAnyone working with code', 2);

-- Design Courses (by Sarah Johnson - user_id: 3)
INSERT INTO courses (title, short_description, description, category, duration, price, discount_price, level, status, image_url, total_lessons, total_students, rating, requirements, what_you_learn, who_is_for, user_id) VALUES
('UI/UX Design Bootcamp', 'Become a professional UI/UX designer', 'Complete UI/UX design course. Learn Figma, design principles, user research, wireframing, prototyping, and how to land your first design job.', 'design', 30, 99.99, 12.99, 'beginner', 'active', 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800', 180, 78500, 4.7, 'No design experience required\nWillingness to practice', 'Create beautiful user interfaces\nConduct user research and testing\nBuild interactive prototypes in Figma\nCreate a portfolio that gets you hired', 'Career changers wanting to enter design\nDevelopers adding design skills\nAnyone interested in UX', 3),

('Figma: UI Design Essential Training', 'Master Figma from zero to hero', 'Learn everything about Figma - the industry standard design tool. Components, auto-layout, prototyping, collaboration, and plugins.', 'design', 15, 59.99, 10.99, 'beginner', 'active', 'https://images.unsplash.com/photo-1609921212029-bb5a28e60960?w=800', 95, 145000, 4.9, 'Computer with internet access\nFree Figma account', 'Master the Figma interface completely\nCreate complex component systems\nBuild interactive prototypes\nCollaborate with teams effectively', 'Designers new to Figma\nDesigners switching from other tools\nDevelopers working with designers', 3),

('Adobe Photoshop CC: Complete Guide', 'Photo editing and graphic design mastery', 'Master Adobe Photoshop from basics to advanced techniques. Photo manipulation, compositing, retouching, and graphic design.', 'design', 25, 79.99, 11.99, 'intermediate', 'active', 'https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=800', 165, 234000, 4.6, 'Photoshop CC installed\nBasic computer skills', 'Master selection and masking techniques\nRetouch photos professionally\nCreate stunning composites\nDesign graphics for any medium', 'Photographers wanting to edit better\nGraphic designers\nContent creators', 3),

('Brand Identity Design: The Complete Course', 'Create memorable brand identities', 'Learn to design complete brand identity systems. Logo design, color theory, typography, brand guidelines, and client presentation.', 'design', 18, 74.99, NULL, 'intermediate', 'active', 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=800', 110, 45600, 4.5, 'Basic design software knowledge\nCreative mindset', 'Design professional logos\nDevelop cohesive brand systems\nCreate comprehensive brand guidelines\nPresent and sell your work to clients', 'Graphic designers\nFreelancers starting their business\nMarketing professionals', 3),

('Web Design Fundamentals', 'Foundation of great web design', 'Free introduction to web design principles. Visual hierarchy, color theory, typography, layout, and responsive design basics.', 'design', 6, 0.00, NULL, 'beginner', 'active', 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800', 42, 520000, 4.4, 'No experience needed\nCuriosity about design', 'Understand visual hierarchy\nChoose effective color schemes\nWork with typography\nCreate balanced layouts', 'Complete beginners\nDevelopers improving their design eye\nAnyone creating websites', 3);

-- Marketing Courses (by Mike Chen - user_id: 4)
INSERT INTO courses (title, short_description, description, category, duration, price, discount_price, level, status, image_url, total_lessons, total_students, rating, requirements, what_you_learn, who_is_for, user_id) VALUES
('Digital Marketing Masterclass', 'Complete digital marketing strategy', 'Learn all aspects of digital marketing: SEO, social media, email marketing, content marketing, PPC advertising, analytics, and strategy.', 'marketing', 45, 119.99, 13.99, 'intermediate', 'active', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800', 280, 98700, 4.6, 'No marketing experience required\nAccess to social media accounts', 'Create comprehensive marketing strategies\nRun profitable ad campaigns\nBuild and grow email lists\nAnalyze and optimize performance', 'Business owners\nMarketing professionals\nEntrepreneurs launching products', 4),

('SEO 2024: Complete SEO Training', 'Rank #1 on Google in 2024', 'Up-to-date SEO strategies that actually work. Keyword research, on-page SEO, technical SEO, link building, and local SEO.', 'marketing', 20, 79.99, 11.99, 'intermediate', 'active', 'https://images.unsplash.com/photo-1562577309-4932fdd64cd1?w=800', 142, 67800, 4.7, 'A website to practice on\nBasic understanding of websites', 'Rank websites higher in Google\nConduct professional keyword research\nFix technical SEO issues\nBuild quality backlinks ethically', 'Website owners\nContent creators\nDigital marketers', 4),

('Social Media Marketing: Strategy & Ads', 'Master social media for business', 'Complete social media marketing course. Content strategy, paid advertising on Facebook, Instagram, LinkedIn, TikTok, and analytics.', 'marketing', 22, 84.99, 12.99, 'beginner', 'active', 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=800', 156, 134500, 4.5, 'Social media accounts\nBusiness or brand to promote', 'Create engaging content strategies\nRun profitable social media ads\nGrow organic following\nMeasure and improve ROI', 'Small business owners\nSocial media managers\nInfluencers and creators', 4),

('Google Ads Mastery: Complete Course', 'Become a Google Ads expert', 'Master Google Ads from scratch. Search ads, display ads, shopping ads, YouTube ads, and conversion optimization.', 'marketing', 28, 99.99, 14.99, 'advanced', 'active', 'https://images.unsplash.com/photo-1553484771-371a605b060b?w=800', 185, 56400, 4.8, 'Google account\nBasic marketing understanding', 'Set up profitable Google Ads campaigns\nOptimize for conversions\nLower cost per acquisition\nScale winning campaigns', 'Marketing professionals\nBusiness owners\nAgency employees', 4),

('Email Marketing & Automation', 'Build and nurture your email list', 'Free email marketing fundamentals. List building, email copywriting, automation sequences, and deliverability best practices.', 'marketing', 8, 0.00, NULL, 'beginner', 'active', 'https://images.unsplash.com/photo-1542744094-3a31f272c490?w=800', 52, 289000, 4.4, 'An email service provider\nA product or content to promote', 'Build high-quality email lists\nWrite emails that convert\nCreate automated email sequences\nImprove deliverability rates', 'Online business owners\nContent creators\nAnyone building an audience', 4);

SELECT 'Seed data inserted successfully!' as message;
SELECT category, COUNT(*) as count, CONCAT('$', ROUND(AVG(price), 2)) as avg_price FROM courses GROUP BY category;
